/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Administrator
 */
public class salesreport extends javax.swing.JFrame {

    /**
     * Creates new form salesreport
     */
    public salesreport() {
         
        initComponents();
        DbConnection.FillConnection();
              fetchgrandtotal1();
        salesfetch();
        reportsearch();
        grandtotal();
  
    }
public void fetchgrandtotal1(){
       
}
    public void salesfetch(){
        try{
        String querysalesfetch="Select *from sales";
        PreparedStatement pstsales=DbConnection.cn.prepareStatement(querysalesfetch);
        ResultSet rssales=pstsales.executeQuery();
        salestable.setModel(DbUtils.resultSetToTableModel(rssales));
                
                
    }
        catch(Exception e){
            
        }
} 

public void reportsearch(){
   
  try{ 
            
            java.util.Date ss= from3.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String from1=sdf.format(ss);
String from2=from1+"00:00:00";
            java.util.Date ss1= to.getDate();
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            String to1 =sdf1.format(ss1);

          String to2=to1+"00:00:00";
            
             
    String querep2="select * from sales where Date >= '"+from2+"' and Date <= '"+to2+"'";
    PreparedStatement ptrep2 = DbConnection.cn.prepareStatement(querep2);
     
  ResultSet rsrep2=ptrep2.executeQuery();
    
    salestable.setModel(DbUtils.resultSetToTableModel(rsrep2));
    
    }catch(Exception e){
    

}

}

public void grandtotal(){
    
    try{
           
             
    String querep3="select ID,GrandTotal,Date from sales where GrandTotal is NOT NULL";
    PreparedStatement ptrep3 = DbConnection.cn.prepareStatement(querep3);
     
  ResultSet rsrep3=ptrep3.executeQuery();
    
    grandtotaltable.setModel(DbUtils.resultSetToTableModel(rsrep3));
    
    }catch(Exception e){
    
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fromgt = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        salestable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        to = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        grandtotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        grandtotaltable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        from3 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("report");
        setMinimumSize(new java.awt.Dimension(1300, 1000));
        getContentPane().setLayout(null);

        salestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "customername", "itemname", "category", "Price", "qty", "Total", "Costprice", "Grandtotal", "Date"
            }
        ));
        jScrollPane1.setViewportView(salestable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 950, 280);

        jPanel1.setLayout(null);

        jLabel1.setText("Sales Report");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(470, 20, 270, 50);
        getContentPane().add(to);
        to.setBounds(310, 50, 120, 30);

        jLabel2.setText("From");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 40, 14);

        jLabel3.setText("TO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 60, 14, 14);
        getContentPane().add(grandtotal);
        grandtotal.setBounds(740, 30, 110, 30);

        jLabel4.setText("Total Sales");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(750, 10, 70, 20);

        grandtotaltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Total", "Date"
            }
        ));
        jScrollPane2.setViewportView(grandtotaltable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(390, 420, 530, 260);

        jButton2.setText("Get TotalSales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(860, 30, 120, 23);

        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 20, 70, 23);
        getContentPane().add(from3);
        from3.setBounds(110, 50, 120, 30);

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 400, 55, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{ 
            
            java.util.Date ss= from3.getDate();
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            String from11=sdf1.format(ss);
String from21=from11+"00:00:00";
            java.util.Date ss11= to.getDate();
            SimpleDateFormat sdf11 = new SimpleDateFormat("yyyy-MM-dd");
            String to11 =sdf11.format(ss11);

          String to21=to11+"00:00:00";
            
             
    String querep21="select id,Grandtotal,Date from sales where Date BETWEEN '"+from21+"' and  '"+to21+"' and Grandtotal is NOT NULL";
    PreparedStatement ptrep21 = DbConnection.cn.prepareStatement(querep21);
     
  ResultSet rsrep21=ptrep21.executeQuery();
    
    grandtotaltable.setModel(DbUtils.resultSetToTableModel(rsrep21));
    
    }catch(Exception e){
    

}
        
        reportsearch();fetchgrandtotal1();
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
int sum1=0;
        for(int m=0; m < grandtotaltable.getRowCount(); m++){
      sum1+=Double.parseDouble(grandtotaltable.getValueAt(m, 1).toString());
        
        } 
        grandtotal.setText(String.valueOf(sum1));

                                           
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
String grandsum=grandtotal.getText(); 

     MessageFormat header = new MessageFormat ("Report Print");
        MessageFormat footer = new MessageFormat ("Total sales:"+grandsum+""+ "");
     
      try
      {
        salestable.print(JTable.PrintMode.NORMAL, header, footer);
      }

      catch (java.awt.print.PrinterException e)
        {
          System.err.format("Cannot Print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesreport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser from3;
    private com.toedter.calendar.JDateChooser fromgt;
    private javax.swing.JTextField grandtotal;
    private javax.swing.JTable grandtotaltable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable salestable;
    private com.toedter.calendar.JDateChooser to;
    // End of variables declaration//GEN-END:variables
}
